name: Build PHP8.0


on:

  push:
    branches: 
      - "8.0"

  schedule:
    - cron: "0 0 * * 4"

  workflow_dispatch:


jobs:

  build_and_publish:
    name: Build and publish Docker image to Docker Hub
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: eworkssk/php-cli
          tags: 8.0
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
